project_id      = "panwlabs-prisma-cloud"
region          = "us-east1"
zone            = "us-east1-c"
cluster_name    = "microseg-john"
#vpc_name    = "panwlabs-prisma-cloud"
#subnet_name = "panwlabs-prisma-cloud"